### PR TITLE
First pass to support bionic

### PR DESCRIPTION
**Pull request by ffdixon**

### CODE REVIEW

**Comment by ak4t0sh** [comment]
@ffdixon FYI by merging this PR you reverted changes from #84. Is it intentional ?

**Comment by ffdixon** [comment]
Ah -- missed the help text for `-d`.  Added it back; otherwise, everything else for the `-d` option should be working on master.

**Comment by hhuseyinpay** [comment]
@ffdixon Is this done? How can I install on bionic? I tried the "-v bionic" and "-v bionic-220" but it failed with "You must run this command on Ubuntu 16.04 server."

**Comment by ffdixon** [comment]
It's still work in progress.  The next version of BigBlueButton will be 2.3 and it will on 18.04 64-bit (bionic), and we'll have `bbb-install.sh` updated to install it.

**Pull request merged**
