### PR TITLE
secure coturn

### PR DESCRIPTION
**Pull request by ghost**
Change configuration, so BBB servers with coTURN are not used for DDoS: https://www.shadowserver.org/what-we-do/network-reporting/accessible-stun-service-report/

### CODE REVIEW

**Comment by kepstin** [comment]
Makes sense to me.

With the turn server co-located on the BigBlueButton server, a separate UDP stun server is never needed, since if a UDP STUN packet could make it to the BBB server, so could a UDP media packet. The primary reason for coturn on a BigBlueButton server is to provide an alternate media path using TCP for when UDP doesn't work at all.

**Comment by kepstin** [comment]
This part of the BigBlueButton config needs to be removed:
https://github.com/bigbluebutton/bbb-install/blob/4f8ad4c4263a4393de5a542eb7a2633cea4c38bb/bbb-install.sh#L1753-L1757
(along with the matching `ref` line below)
since that attempts to connect to the TURN server over UDP, which is no longer available.

**Comment by antobinary** [comment]
Thank you for this contribution @opensourcecompany !

**Comment by Merlinux-source** [comment]
@JohnHammond @LiveOverflow @PwnFunction @BrodieRobertson

**Comment by prlanzarin** [comment]
FYI there's a secondary reason for TURN over UDP + co-located coturn which is to minimize the impact of the forced relay transport policy for Firefox endpoints (ICE-lite issue).

I believe the colocated coturn configuration already mitigates such DDoS vectors by restricting relay and peer IPs, so I don't think the default installation is affected:
```
relay-ip=${INTERNAL_IP:-$IP}
no-loopback-peers
no-multicast-peers
denied-peer-ip=0.0.0.0-255.255.255.255
denied-peer-ip=::-ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff
allowed-peer-ip=$IP $SECOND_ALLOWED_PEER_IP
```

**Pull request closed without merging**
