### PR TITLE
focal-260: Added installation of Greenlight-v3 and removed the previous of Greenlight-v2.

### PR DESCRIPTION
**Pull request by KH-Amir-TN**
This PR adds in the logic to install and update Greenlight version 3.
It was made with this conditions in mind:
1. The logic should be simple to understand and coherent with the rest of logic in the script.
2. Replaying the installation process is safe and triggers an upgrade to greenlight-v3.
3. Admins who already used  `bbb-install-2.6` should have a minimal to low impact after these changes.
4. The logic shouldn't overlap with any other functionality.

## NOTES FOR ADMINS:
Admins who already used `bbb-install-2.6` can replay the script with these limitations in mind:
1. It's required to trigger `install_ssl` logic through providing the email and hostname `-s bbb.example.com -e info@example.com` to update the `/etc/nginx/sites-available/bigbluebutton`.
2. After the update Greenlight-v3 will be used by default, Greenlight-v2 will not be removed by the script.
It's up to the admins to decide when to remove greenlight-v2.
However, to access greenlight-v2 an explicit `https://bbb.example.com/b` needs to be provided otherwise greenlight-v3 will be serverd.
3. Admins will experience a problem with hosting both version of Greenlight on the same system:
The problem will impact the presentation upload on both version and users avatars on greenlight-v3.
Admins are invited to manually remove these [LINES](https://github.com/bigbluebutton/greenlight/blob/master/greenlight.nginx#L39-L44)  in ` /usr/share/bigbluebutton/nginx/greenlight.nginx`. and reload|restart nginx by `nginx -s reload`.
Keep in mind after such change only greenlight-v3 active storage will be fully accessible and not greenlight-v2.
If admins are willing to continue providing their services on greenlight-v2 then they're invited to use a different environment for greenlight-v3 where no issues should be faced.

### CODE REVIEW

**Comment by farhatahmad** [comment]
1. The script should automatically install greenlight version 3 with Bigbluebutton 2.6 without breaking any of BBB services.
2. The script can install greenlight version 3 and update it to the latest version on replay (pick any changes to nginx file, pull all GL3.0 services images,..).
3. The script can install greenlight version 3 even on systems running an old version of the script and even having greenlight version 2 installed.

**Comment by BrentBaccala** [comment]
I ran this script and it installed without error, however, I'm wondering if it should set more variables in the `/root/greenlight-v3/.env` file.

The [Greenlight v3 installation instructions](https://docs.bigbluebutton.org/greenlight_v3/gl3-install.html) list `DOMAIN_NAME`, `GL_HOSTNAME`, `POSTGRES_PASSWORD` as required values, but I don't see any of them set.

Should they be set?  Should a `KEYCLOAK_PASSWORD` be set?  If not, how do I create an admin user.  The old `rake admin:create` and `rake user:create` tasks are no longer present.

**Comment by antobinary** [comment]
I tested both clean installation
and
installing over an existing BBB (2.6.0-rc.1) with Greenlight v2.

All points I had were addressed in beta.14 and beta.15 of Greenlight.

**Comment by amishbhavsar** [comment]
I agree with [BrentBaccala](https://github.com/BrentBaccala)
I did a clean install of [BigBlueButton 2.6.0-rc.2](https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.6.0-rc.2) using the [bbb-install-2.6.sh](https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install-2.6.sh) script.
The installation went without any issues. Greenlight V3 beta 15 was installed, but there is no KeyCloak. Also, I am not sure if there is any documentation on how to set up admin user on Local Account?

**Comment by ffdixon** [comment]
See GreenLight V3 documentation for information on [setting up an admin account](https://docs.bigbluebutton.org./greenlight/gl-admin.html#creating-a-user-account).

**Comment by amishbhavsar** [comment]
Hi Fred, thanks for the quick response, but I think the link you shared points to documentation for Greenlight V2. I am asking for setting up admin account for Greenlight V3.

**Comment by antobinary** [comment]
There's a new section about Greenlight v3 in the docs website https://docs.bigbluebutton.org/
Screenshot from 2023-02-04 06-20-05

**Comment by amishbhavsar** [comment]
Hi,
I think that there is a disconnect with the documentation.
Let me share a few examples:
1. No info on setting up admin users as **local account** on Greenlight V3 here: https://docs.bigbluebutton.org/greenlight_v3/gl3-install.html
2. No Keycloak installation happened when doing a fresh install of BBB 2.6 RC 2 although the documentations here says "By default, Greenlight ships with Keycloak to provide system administrators an easy way ..." here: https://docs.bigbluebutton.org/greenlight_v3/gl3-install.html
3. Also, as per the document, it says that there are 2 .env files in Greenlight V3
~/greenlight-run/.env (for the entire deployment)
~/greenlight-run/data/greenlight/.env (for Greenlight ONLY)
But in reality, there is only 1 .env file. (see pic: https://pasteboard.co/ndoQNNoyiIS5.jpg)
4. Finally, the documentation says folder name: greenlight-run, but there is no such folder.

**Comment by ffdixon** [comment]
Thanks, and your right.  

GreenLight V3 is getting closer to official release, but the documentation is still a step behind the current build.

You should see updates to all of these items early next week.  If you can see the changes needed and want to jump start, we would welcome a pull request as well.

**Pull request merged**
