### PR TITLE
focal-260: Added Keycloak installation.

### PR DESCRIPTION
**Pull request by KH-Amir-TN**
This PR tends to add in the logic to install Keycloak along with Greenlight through the `-k` option.

Admins can Deploy Greenlight and Keycloak at once by providing `-k` option OR deploy Greenlight only by omitting the `-k` option and add in Keycloak at a later point through the use of the same option.
After the setup Keycloak can be considered a dependency of Greenlight like redis and postgres services therefore upgrading Keycloak is part of upgrading Greenlight (`-k` is only required for the addition of Keycloak and can be omitted on upgrades).

### CODE REVIEW

**Comment by hiroshisuga** [comment]
When I already have GLv2 running, Keycloak won't start because the postgres DB cannot be created (conflict with the postgre from GLv2).

Error message:
.....
docker.io/bigbluebutton/greenlight:v3
bbb-install: checking the configuration of greenlight-v3...
bbb-install: added greenlight-v3 nginx file
bbb-install: Adding Keycloak...
Creating network "greenlight-v3_default" with the default driver
Creating postgres ... error

ERROR: for postgres  Cannot create container for service postgres: Conflict. The container name "/postgres" is already in use by container "xxxx". You have to remove (or rename) that container to be able to reuse that name.

ERROR: for postgres  Cannot create container for service postgres: Conflict. The container name "/postgres" is already in use by container "xxxx". You have to remove (or rename) that container to be able to reuse that name.
ERROR: Encountered errors while bringing up the project.
ERROR: No container found for postgres_1
bbb-install: unable to create Keycloak DB

Do I misunderstand something?

**Comment by KH-Amir-TN** [comment]
Hi @hiroshisuga ,
Thanks for dedicating time to test our changes and share your feedback.

I've tried to replicate your case through the following deployment:
- On a clean system I've run bbb-install-2.6 release f4cb7ac with `-g` resulting in installing BBB 2.6 along with GL2.0.
- Upgraded the system using bbb-install-2.6 release 91dd5c8 with `-g` resulting in upgrading BBB2.6 and installing GL3.0.
- Upgraded the system using bbb-install-2.6 latest release with `-gk` resulting in upgrading BBB2.6 and GL3.0 while installing Keycloak.

In all steps no issues were discovered on my side so I couldn't replicate your issue.
Can you share with me more context?

I see that the errors `The container name "/postgres" is already in use by container "xxxx"` and `ERROR: No container found for postgres_1` may be indicating that there's a container `XXX` named `postgres` running on the same system but not through the `/root/greenlight-v3/docker-compose.yml` so it couldn't manage it.

Currently we're expecting the script to be run on a clean system dedicated to host BBB 2.6 components only so the services aren't namespaced (scoped) making a room for an overlap with other systems (postgres, keycloak, redis container names are subject to this, also host ports TCP 5000 and 5432 (GL 2.0) and TCP 5050 & 5151 (GL3.0)).

Regards,
Amir,

**Comment by hiroshisuga** [comment]
Hi @KH-Amir-TN ,
Thanks for the detailed explanation! With your information, I have finally managed to run the script without errors. Now GLv3 with keycloak is running together with GLv2 without problems.

Let me first explain the context.

I was trying to upgrade, during holidays, one of my servers which still some people are using for online lecture. Thus running Greenlight v2 after upgrading was quite important. GLv2 was installed in my normal user account, not in the root account which the bbb-install script may expect.
As you suspected, my server has been updated many many times since BBB2.2 (I even upgraded Ubuntu). There has been many unused docker images and old configurations. Although I know it's not what the script is intended, I guess people like me are not the minority. I do not mean that the developers need to see every case, but we'd better prepare for many reckless users like me asking questions. I'd be happy if my post helps you a bit.

Now here is what I did. I don't know what hit the problem actually. 
It seems that it's just a matter of naming of docker container. So I changed the container names.
- open docker-compose.yml in the root account directory (for GLv3; it's already there as I failed running bbb-install many times), and change container_names as postgres -> postgres-glv3 and keycloak -> keycloak-glv3.
- open docker-compose.yml in my normal user account home directory (GLv2 installed), and add the line "container_name: greenlight-v2" at the app directive. This line has been missing. 

Then I removed all unnecessary and unused docker images and containers, just leaving the minimal containers needed for running GLv2. 

Then I re-run bbb-install script again. 

As I mentioned, I don't know what has actually solved the problem. I hope it helps!

**Comment by KH-Amir-TN** [comment]
> Hi @KH-Amir-TN , Thanks for the detailed explanation! With your information, I have finally managed to run the script without errors. Now GLv3 with keycloak is running together with GLv2 without problems.
> 
> Let me first explain the context.
> 
> I was trying to upgrade, during holidays, one of my servers which still some people are using for online lecture. Thus running Greenlight v2 after upgrading was quite important. GLv2 was installed in my normal user account, not in the root account which the bbb-install script may expect. As you suspected, my server has been updated many many times since BBB2.2 (I even upgraded Ubuntu). There has been many unused docker images and old configurations. Although I know it's not what the script is intended, I guess people like me are not the minority. I do not mean that the developers need to see every case, but we'd better prepare for many reckless users like me asking questions. I'd be happy if my post helps you a bit.
> 
> Now here is what I did. I don't know what hit the problem actually. It seems that it's just a matter of naming of docker container. So I changed the container names.
> 
> * open docker-compose.yml in the root account directory (for GLv3; it's already there as I failed running bbb-install many times), and change container_names as postgres -> postgres-glv3 and keycloak -> keycloak-glv3.
> * open docker-compose.yml in my normal user account home directory (GLv2 installed), and add the line "container_name: postgres-glv2" at the db directive. This line has been missing.
> 
> Then I removed all unnecessary and unused docker images and containers, just leaving the minimal containers needed for running GLv2.
> 
> Then I re-run bbb-install script again.
> 
> As I mentioned, I don't know what has actually solved the problem. I hope it helps!

Hi @hiroshisuga ,
Thanks for sharing your context as we can benefit from it in the future!

Glad to see that you've managed to run the script without encountering any issues therefore benefiting from our latest changes.

It makes me happy to see that our changes managed to work on such a unique deployment.
Indeed there's room for improvement to further support and tolerate exigent systems which will address in the near future - 
 Currently we're working on meeting the complete BBB2.6 ecosystem for release.
Meanwhile, if you happen to come across any issues on your system or you have any improvement/feature requests please let us know.

I kindly invite you to check the guides on [creating an admin account](https://docs.bigbluebutton.org/greenlight_v3/gl3-install.html#creating-an-admin-account-1) on GL3.0 so you can start configuring and customizing your organization.
Since you already have an active deployment of GL2.0 I invite you also to [setup SMTP](https://docs.bigbluebutton.org/greenlight_v3/gl3-install.html#email-setup)  and use our [migration system](https://docs.bigbluebutton.org/greenlight_v3/gl3-migration.html) to slowly migrate your data to GL3.0.
After confirming the migration success and at your own pace you can announce the upgrade to GL3.0 to your users and request them to reset their passwords using the same emails **if using local accounts** or simply configure GL3.0 to use an [open ID provider](https://docs.bigbluebutton.org/greenlight_v3/gl3-install.html#openid-connect-setup) before migrating - We recommend and support [Keycloak](https://www.keycloak.org/) which you can configure easily to use your existing Identity providers before migrating your data to GL3.0 in such case your users should be able to connect to GL3.0 through a SSO via Keycloak without having to reset any passwords and while having their old data setup from GL2.0!

Hope that helps.

Sincerely,
Amir,

**Comment by hiroshisuga** [comment]
Hi @KH-Amir-TN , thanks a lot for the guide. It helps a lot!
I am using only the authentication from MS as we have only students and professors in the same university, which has the corporate license. I use Keycloak and as you say, we do not need the password migration (or reset) in this case. However, I have encountered into a strange problem that migrated user cannot login. 

Since this is an already closed PR, I opened this issue in Google group.
https://groups.google.com/g/bigbluebutton-dev/c/ZdnJOx4pO6w

**Pull request merged**
