### PR TITLE
fix: tomcat fails to start on some machines

### PR DESCRIPTION
**Pull request by matinzd**
This patch fixes starting tomcat on some machines that have more cores.

### CODE REVIEW

**Comment by ffdixon** [comment]
Thanks for the pull request -- can you give more information on why this is needed.  I've checked a few long running BigBlueButton servers and they all have default value of 1024.

**Comment by matinzd** [comment]
> Thanks for the pull request -- can you give more information on why this is needed. I've checked a few long running BigBlueButton servers and they all have default value of 1024.

We had problem on our servers with this option. :)

**Comment by mclegrand** [comment]
dedicated server with 56 here too, spent 5 hours yesterday trying to install bbb.

This fixed it for me, THANKS YOU

**Comment by matinzd** [comment]
I think this fixed in https://github.com/bigbluebutton/bbb-install/commit/e58a3c0b36b7b7b4b34ec380d744fc05dc4e7d84. Will close!

**Pull request closed without merging**
