### PR TITLE
Override some service options when installing in a LXC container

### PR DESCRIPTION
**Pull request by dashohoxha**
Related issues: #14, https://github.com/bigbluebutton/bigbluebutton/issues/11137

### CODE REVIEW

**Comment by ffdixon** [comment]
Thanks @dashohoxha !

**Comment by dashohoxha** [comment]
It seems like the LXC containers need the capability CAP_SYS_NICE in order to be able to set a realtime scheduler. I tried to set it to my container with a command like this: `lxc config set BBB raw.lxc=lxc.cap.keep=sys_nice`, however the container wouldn't start afterwards. Maybe I didn't do it correctly.

If this capability is added to the container, maybe the services will start without these modifications.

**Comment by dashohoxha** [comment]
I am trying to get some help from the LXD community:
https://discuss.linuxcontainers.org/t/setting-capabilities-to-the-lxc-containers/17007

**Comment by dashohoxha** [comment]
> I am trying to get some help from the LXD community: https://discuss.linuxcontainers.org/t/setting-capabilities-to-the-lxc-containers/17007

There is no answer there yet. I understand that capabilities are a bit complex and the tools for managing them are not yet mature enough.

To check whether the CAP_SYS_NICE is available or not, I am now using a trick that I found in `bbb-install.sh`: grep for `SETSCHEDULER` in the output of the `systemctl status freeswitch`. If this error message is present, it means that CAP_SYS_NICE is not available and we need to customize a few services, so that they don't require realtime scheduling (which would make these services fail to start).

@ffdixon can we review and merge this PR? I am done with it.

**Comment by ffdixon** [comment]
Thanks for the pull request -- will review.

**Comment by dashohoxha** [comment]
There is a new answer on the LXD community:  
https://discuss.linuxcontainers.org/t/setting-capabilities-to-the-lxc-containers/17007/5  
But I don't think that anything needs to be changed on the pull request.

**Review by ffdixon — APPROVED** [review]
Looks good -- thanks for the pull request!

**Comment by dashohoxha** [comment]
> Looks good -- thanks for the pull request!

Someone should merge it, because I am not able to do it.

**Pull request merged**
